name: Nofall
version: 1.1
main: me.Desiney.Nofall.Main
authors: KubixDesiney
description: Teleport to spawn when you fall into the void!

commands:
  Nofall:
    description: Settings for Nofall
    permission: Nofall.cmd
    permission-message: &cNo Permss1on.
